{% set version = "2.1.9" %}

package:
  name: bob.core
  version: {{ version }}

source:
  fn: bob.core-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.core/bob.core-{{ version }}.zip
  md5: e6bd43759569e6f3b543463ca24c4b0b

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - cmake
    - pkg-config
    - bob.blitz
    - boost 1.63.*

  run:
    - python
    - bob.blitz
    - boost 1.63.*

test:
  requires:
    - nose

  imports:
    - bob
    - bob.core
    - bob.core.random

  commands:
    - nosetests -sv bob.core

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  summary: Logging and RNG for Bob

extra:
  recipe-maintainers:
    - 183amir
