{% set version = "2.1.6" %}

package:
  name: bob.core
  version: {{ version }}

source:
  fn: bob.core-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.core/bob.core-{{ version }}.zip
  md5: 954e71c130b4e4d77a0ec2a5f13e8bb6

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - cmake
    - pkg-config
    - bob.blitz
    - boost 1.62.*

  run:
    - python
    - bob.blitz
    - boost 1.62.*

test:
  requires:
    - nose

  imports:
    - bob
    - bob.core
    - bob.core.random

  commands:
    - nosetests -sv bob.core

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Logging and RNG for Bob

extra:
  recipe-maintainers:
    - 183amir
